import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#16211A',
  },
  safeArea: {
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
    paddingBottom: 116,
  },
  panel: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    gap: 22,
    borderRadius: 8,
    backgroundColor: '#F8F0E3',
    padding: 22,
    elevation: 8,
    ...Platform.select({
      web: {
        boxShadow: '0 16px 24px rgba(0, 0, 0, 0.24)',
      },
      default: {
        shadowColor: '#000000',
        shadowOpacity: 0.24,
        shadowRadius: 24,
        shadowOffset: { width: 0, height: 16 },
      },
    }),
  },
  header: {
    gap: 10,
  },
  badge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#2B3A2E',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  badgeText: {
    color: '#F8F0E3',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  title: {
    color: '#172116',
    fontSize: 52,
    fontWeight: '900',
    lineHeight: 56,
  },
  subtitle: {
    color: '#62584C',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 23,
  },
  section: {
    gap: 12,
  },
  sectionLabel: {
    color: '#172116',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  counterCard: {
    minHeight: 104,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderColor: '#172116',
  },
  counterValue: {
    color: '#172116',
    fontSize: 44,
    fontWeight: '900',
    lineHeight: 48,
  },
  stepper: {
    flexDirection: 'row',
    gap: 10,
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F25C54',
    borderWidth: 2,
    borderColor: '#172116',
  },
  disabledButton: {
    opacity: 0.4,
  },
  iconButtonText: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 28,
  },
  roleGrid: {
    gap: 10,
  },
  roleCard: {
    minHeight: 72,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2D4C4',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  roleCopy: {
    flex: 1,
    gap: 3,
  },
  roleName: {
    color: '#172116',
    fontSize: 16,
    fontWeight: '900',
  },
  roleDescription: {
    color: '#62584C',
    fontSize: 13,
    fontWeight: '700',
  },
  roleStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  roleButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#172116',
  },
  roleButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 22,
  },
  roleCount: {
    minWidth: 24,
    color: '#172116',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  helperText: {
    color: '#62584C',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  nameGrid: {
    gap: 10,
  },
  nameInput: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2D4C4',
    paddingHorizontal: 14,
    color: '#172116',
    fontSize: 16,
    fontWeight: '700',
  },
  choiceRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  choiceButton: {
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: '#FFF9F0',
    borderWidth: 1,
    borderColor: '#D4C4B4',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  choiceButtonSelected: {
    backgroundColor: '#E4F0DB',
    borderColor: '#7B9E67',
  },
  choiceText: {
    color: '#62584C',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  choiceTextSelected: {
    color: '#2F5D2F',
  },
  packRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  packButton: {
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#172116',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  packText: {
    color: '#172116',
    fontSize: 14,
    fontWeight: '900',
  },
  packTextSelected: {
    color: '#FFFFFF',
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#172116',
    paddingHorizontal: 18,
  },
  startButton: {
    backgroundColor: '#2F9E44',
  },
  primaryButtonCompact: {
    minHeight: 58,
    flex: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#172116',
    paddingHorizontal: 18,
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: '#F8F0E3',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryButton: {
    minHeight: 58,
    flex: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#172116',
    paddingHorizontal: 18,
  },
  secondaryButtonText: {
    color: '#172116',
    fontSize: 16,
    fontWeight: '900',
  },
  pressed: {
    opacity: 0.76,
    transform: [{ scale: 0.99 }],
  },
  roundTopper: {
    gap: 8,
  },
  overline: {
    color: '#F25C54',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  roundTitle: {
    color: '#172116',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
  },
  secretCard: {
    minHeight: 260,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: '#172116',
    backgroundColor: '#2D9CDB',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    padding: 24,
  },
  secretCardCivilian: {
    backgroundColor: '#2F9E44',
  },
  secretCardImposter: {
    backgroundColor: '#F25C54',
  },
  secretCardSpy: {
    backgroundColor: '#F4A261',
  },
  secretCardEyebrow: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  secretCardText: {
    color: '#FFFFFF',
    fontSize: 44,
    fontWeight: '900',
    lineHeight: 50,
    textAlign: 'center',
  },
  secretCardHint: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    textAlign: 'center',
  },
  roundBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#2D9CDB',
    borderWidth: 2,
    borderColor: '#172116',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  roundBadgeText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  statusGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  statusBox: {
    flex: 1,
    minHeight: 86,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2D4C4',
    justifyContent: 'center',
    padding: 14,
  },
  statusValue: {
    color: '#172116',
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
  },
  statusLabel: {
    color: '#62584C',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  voteList: {
    gap: 10,
  },
  voteButton: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2D4C4',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
  },
  voteButtonSelected: {
    backgroundColor: '#172116',
    borderColor: '#172116',
  },
  playerList: {
    gap: 10,
  },
  playerPill: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2D4C4',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
  },
  playerNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#172116',
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 28,
    textAlign: 'center',
  },
  playerNumberSelected: {
    backgroundColor: '#F8F0E3',
    color: '#172116',
  },
  playerName: {
    color: '#172116',
    fontSize: 16,
    fontWeight: '800',
  },
  votePlayerNameSelected: {
    color: '#F8F0E3',
  },
  resultCard: {
    borderRadius: 8,
    borderWidth: 3,
    borderColor: '#172116',
    backgroundColor: '#FFFFFF',
    padding: 22,
    gap: 8,
  },
  safeResultCard: {
    backgroundColor: '#E8F6EA',
  },
  dangerResultCard: {
    backgroundColor: '#FDE8E7',
  },
  resultName: {
    color: '#172116',
    fontSize: 38,
    fontWeight: '900',
    lineHeight: 42,
  },
  resultWord: {
    color: '#62584C',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
  },
});
