import type { WordPack } from './types';

export const categoryPacks: WordPack[] = [
  {
    id: 'dyr',
    label: 'Dyr',
    color: '#F25C54',
    words: [
      'Panter',
      'Jaguar',
      'Flamingo',
      'Krokodille',
      'Gorilla',
      'Delfin',
      'Ørn',
      'Falk',
      'Pingvin',
      'Kameleon',
      'Skorpion',
      'Python',
      'Panda',
      'Koala',
      'Hval',
      'Hai',
      'Reinsdyr',
      'Lama',
      'Alpakka',
      'Gepard',
    ],
  },
  {
    id: 'mat',
    label: 'Mat',
    color: '#2D9CDB',
    words: [
      'Sushi',
      'Tapas',
      'Espresso',
      'Croissant',
      'Trøffel',
      'Kaviar',
      'Wasabi',
      'Kimchi',
      'Paella',
      'Falafel',
      'Safran',
      'Mango',
      'Parmesan',
      'Gelato',
      'Taco',
      'Curry',
      'Ramen',
      'Hummus',
      'Bruschetta',
      'Mozzarella',
    ],
  },
  {
    id: 'ting',
    label: 'Ting',
    color: '#7CB342',
    words: [
      'Kompass',
      'Kikkert',
      'Drone',
      'Mikrofon',
      'Kamera',
      'Pass',
      'Kart',
      'Vinyl',
      'Parfyme',
      'Skateboard',
      'Sjakk',
      'Poker',
      'Maskerade',
      'Krone',
      'Kapsel',
      'Lommelykt',
      'Koffert',
      'Lasso',
      'Rustning',
      'Teleskop',
    ],
  },
  {
    id: 'steder',
    label: 'Steder',
    color: '#F4A261',
    words: [
      'Paris',
      'Roma',
      'Tokyo',
      'Dubai',
      'Monaco',
      'Venezia',
      'Barcelona',
      'København',
      'Reykjavík',
      'New York',
      'Rio',
      'Bali',
      'Svalbard',
      'Sahara',
      'Amazonas',
      'Alaska',
      'Himalaya',
      'Antarktis',
      'Galápagos',
      'Santorini',
    ],
  },
  {
    id: 'landemerker',
    label: 'Landemerker',
    color: '#6C63FF',
    words: [
      'Machu Picchu',
      'Eiffeltårnet',
      'Big Ben',
      'Taj Mahal',
      'Colosseum',
      'Louvre',
      'Akropolis',
      'Stonehenge',
      'Pompeii',
      'Angkor Wat',
      'Petra',
      'Versailles',
      'Kreml',
      'Sfinxen',
      'Burj Khalifa',
      'Frihetsgudinnen',
      'Operahuset',
      'Notre-Dame',
      'Alhambra',
      'Kilimanjaro',
      'Niagara',
    ],
  },
  {
    id: 'rommet',
    label: 'Rommet',
    color: '#00897B',
    words: [
      'Pluto',
      'Mars',
      'Venus',
      'Saturn',
      'Jupiter',
      'Merkur',
      'Neptun',
      'Månen',
      'Solen',
      'Galakse',
      'Komet',
      'Asteroide',
      'Meteor',
      'Supernova',
      'Stjernetåke',
      'Romstasjon',
      'Rakett',
      'Astronaut',
      'Melkeveien',
      'Solsystem',
    ],
  },
  {
    id: 'natur',
    label: 'Natur',
    color: '#D1495B',
    words: [
      'Diamant',
      'Rubin',
      'Smaragd',
      'Gull',
      'Sølv',
      'Krystall',
      'Vulkan',
      'Lava',
      'Isfjell',
      'Nordlys',
      'Korallrev',
      'Regnskog',
      'Geysir',
      'Fossil',
      'Orkan',
      'Tsunami',
      'Fjord',
      'Grotte',
      'Lagune',
      'Oase',
    ],
  },
  {
    id: 'kultur',
    label: 'Kultur',
    color: '#9B5DE5',
    words: [
      'Mona Lisa',
      'Viking',
      'Samurai',
      'Jazz',
      'Opera',
      'Ballett',
      'Graffiti',
      'Festival',
      'Karneval',
      'Shakespeare',
      'Picasso',
      'Bowie',
      'Banksy',
      'Mozart',
      'Hollywood',
      'Broadway',
      'Manga',
      'Flamenco',
      'Mythologi',
      'Tango',
    ],
  },
];

export const RELATED_WORDS: Record<string, string> = {
  Panter: 'Jaguar',
  Jaguar: 'Panter',
  Flamingo: 'Pingvin',
  Pingvin: 'Flamingo',
  Krokodille: 'Python',
  Python: 'Krokodille',
  Gorilla: 'Panda',
  Panda: 'Gorilla',
  Delfin: 'Hval',
  Hval: 'Delfin',
  Ørn: 'Falk',
  Falk: 'Ørn',
  Kameleon: 'Skorpion',
  Skorpion: 'Kameleon',
  Koala: 'Alpakka',
  Alpakka: 'Koala',
  Hai: 'Gepard',
  Gepard: 'Hai',
  Reinsdyr: 'Lama',
  Lama: 'Reinsdyr',
  Sushi: 'Ramen',
  Ramen: 'Sushi',
  Tapas: 'Bruschetta',
  Bruschetta: 'Tapas',
  Espresso: 'Croissant',
  Croissant: 'Espresso',
  Trøffel: 'Kaviar',
  Kaviar: 'Trøffel',
  Wasabi: 'Kimchi',
  Kimchi: 'Wasabi',
  Paella: 'Curry',
  Curry: 'Paella',
  Falafel: 'Hummus',
  Hummus: 'Falafel',
  Safran: 'Parmesan',
  Parmesan: 'Safran',
  Mango: 'Gelato',
  Gelato: 'Mango',
  Taco: 'Mozzarella',
  Mozzarella: 'Taco',
  Kompass: 'Kart',
  Kart: 'Kompass',
  Kikkert: 'Teleskop',
  Teleskop: 'Kikkert',
  Drone: 'Kamera',
  Kamera: 'Drone',
  Mikrofon: 'Vinyl',
  Vinyl: 'Mikrofon',
  Pass: 'Koffert',
  Koffert: 'Pass',
  Parfyme: 'Maskerade',
  Maskerade: 'Parfyme',
  Skateboard: 'Lasso',
  Lasso: 'Skateboard',
  Sjakk: 'Poker',
  Poker: 'Sjakk',
  Krone: 'Rustning',
  Rustning: 'Krone',
  Kapsel: 'Lommelykt',
  Lommelykt: 'Kapsel',
  Paris: 'Roma',
  Roma: 'Paris',
  Tokyo: 'Dubai',
  Dubai: 'Tokyo',
  Monaco: 'Santorini',
  Santorini: 'Monaco',
  Venezia: 'Barcelona',
  Barcelona: 'Venezia',
  København: 'Reykjavík',
  Reykjavík: 'København',
  'New York': 'Rio',
  Rio: 'New York',
  Bali: 'Galápagos',
  Galápagos: 'Bali',
  Svalbard: 'Alaska',
  Alaska: 'Svalbard',
  Sahara: 'Amazonas',
  Amazonas: 'Sahara',
  Himalaya: 'Antarktis',
  Antarktis: 'Himalaya',
  'Machu Picchu': 'Petra',
  Petra: 'Machu Picchu',
  Eiffeltårnet: 'Big Ben',
  'Big Ben': 'Eiffeltårnet',
  'Taj Mahal': 'Versailles',
  Versailles: 'Taj Mahal',
  Colosseum: 'Akropolis',
  Akropolis: 'Colosseum',
  Louvre: 'Mona Lisa',
  Stonehenge: 'Pompeii',
  Pompeii: 'Stonehenge',
  'Angkor Wat': 'Alhambra',
  Alhambra: 'Angkor Wat',
  Kreml: 'Notre-Dame',
  'Notre-Dame': 'Kreml',
  Sfinxen: 'Kilimanjaro',
  Kilimanjaro: 'Sfinxen',
  'Burj Khalifa': 'Frihetsgudinnen',
  Frihetsgudinnen: 'Burj Khalifa',
  Operahuset: 'Niagara',
  Niagara: 'Operahuset',
  Pluto: 'Neptun',
  Neptun: 'Pluto',
  Mars: 'Venus',
  Venus: 'Mars',
  Saturn: 'Jupiter',
  Jupiter: 'Saturn',
  Merkur: 'Solsystem',
  Solsystem: 'Merkur',
  Månen: 'Solen',
  Solen: 'Månen',
  Galakse: 'Melkeveien',
  Melkeveien: 'Galakse',
  Komet: 'Asteroide',
  Asteroide: 'Komet',
  Meteor: 'Supernova',
  Supernova: 'Meteor',
  Stjernetåke: 'Romstasjon',
  Romstasjon: 'Stjernetåke',
  Rakett: 'Astronaut',
  Astronaut: 'Rakett',
  Diamant: 'Rubin',
  Rubin: 'Diamant',
  Smaragd: 'Krystall',
  Krystall: 'Smaragd',
  Gull: 'Sølv',
  Sølv: 'Gull',
  Vulkan: 'Lava',
  Lava: 'Vulkan',
  Isfjell: 'Nordlys',
  Nordlys: 'Isfjell',
  Korallrev: 'Lagune',
  Lagune: 'Korallrev',
  Regnskog: 'Oase',
  Oase: 'Regnskog',
  Geysir: 'Fossil',
  Fossil: 'Geysir',
  Orkan: 'Tsunami',
  Tsunami: 'Orkan',
  Fjord: 'Grotte',
  Grotte: 'Fjord',
  'Mona Lisa': 'Picasso',
  Picasso: 'Mona Lisa',
  Viking: 'Samurai',
  Samurai: 'Viking',
  Jazz: 'Opera',
  Opera: 'Jazz',
  Ballett: 'Flamenco',
  Flamenco: 'Ballett',
  Graffiti: 'Banksy',
  Banksy: 'Graffiti',
  Festival: 'Karneval',
  Karneval: 'Festival',
  Shakespeare: 'Mozart',
  Mozart: 'Shakespeare',
  Bowie: 'Hollywood',
  Hollywood: 'Bowie',
  Broadway: 'Tango',
  Tango: 'Broadway',
  Manga: 'Mythologi',
  Mythologi: 'Manga',
};

export const allWords = Array.from(new Set(categoryPacks.flatMap((pack) => pack.words)));

export const wordPacks: WordPack[] = [
  {
    id: 'alt',
    label: 'Alle',
    color: '#172116',
    words: allWords,
  },
  ...categoryPacks,
];

function pickFallbackWord(words: string[]) {
  return words[Math.floor(Math.random() * words.length)];
}

export function getRelatedWord(word: string) {
  const relatedWord = RELATED_WORDS[word];

  if (relatedWord) {
    return relatedWord;
  }

  const sourcePack = categoryPacks.find((pack) => pack.words.includes(word));
  const alternatives = (sourcePack?.words ?? allWords).filter((alternative) => alternative !== word);

  return alternatives.length > 0 ? pickFallbackWord(alternatives) : word;
}
