import type { WordPack } from './types';

const normalWords = [
  'Panter',
  'Jaguar',
  'Flamingo',
  'Krokodille',
  'Gorilla',
  'Delfin',
  'Ørn',
  'Falk',
  'Pingvin',
  'Kameleon',
  'Skorpion',
  'Python',
  'Panda',
  'Koala',
  'Hval',
  'Hai',
  'Reinsdyr',
  'Lama',
  'Alpakka',
  'Gepard',
  'Sushi',
  'Tapas',
  'Espresso',
  'Croissant',
  'Trøffel',
  'Kaviar',
  'Wasabi',
  'Kimchi',
  'Paella',
  'Falafel',
  'Safran',
  'Mango',
  'Parmesan',
  'Gelato',
  'Taco',
  'Curry',
  'Ramen',
  'Hummus',
  'Bruschetta',
  'Mozzarella',
  'Kompass',
  'Kikkert',
  'Drone',
  'Mikrofon',
  'Kamera',
  'Pass',
  'Kart',
  'Vinyl',
  'Parfyme',
  'Skateboard',
  'Sjakk',
  'Poker',
  'Maskerade',
  'Krone',
  'Kapsel',
  'Lommelykt',
  'Koffert',
  'Lasso',
  'Rustning',
  'Teleskop',
  'Paris',
  'Roma',
  'Tokyo',
  'Dubai',
  'Monaco',
  'Venezia',
  'Barcelona',
  'København',
  'Reykjavík',
  'New York',
  'Rio',
  'Bali',
  'Svalbard',
  'Sahara',
  'Amazonas',
  'Alaska',
  'Himalaya',
  'Antarktis',
  'Galápagos',
  'Santorini',
  'Machu Picchu',
  'Eiffeltårnet',
  'Big Ben',
  'Taj Mahal',
  'Colosseum',
  'Louvre',
  'Akropolis',
  'Stonehenge',
  'Pompeii',
  'Angkor Wat',
  'Petra',
  'Versailles',
  'Kreml',
  'Sfinxen',
  'Burj Khalifa',
  'Frihetsgudinnen',
  'Operahuset',
  'Notre-Dame',
  'Alhambra',
  'Kilimanjaro',
  'Niagara',
  'Pluto',
  'Mars',
  'Venus',
  'Saturn',
  'Jupiter',
  'Merkur',
  'Neptun',
  'Månen',
  'Solen',
  'Galakse',
  'Komet',
  'Asteroide',
  'Meteor',
  'Supernova',
  'Stjernetåke',
  'Romstasjon',
  'Rakett',
  'Astronaut',
  'Melkeveien',
  'Solsystem',
  'Diamant',
  'Rubin',
  'Smaragd',
  'Gull',
  'Sølv',
  'Krystall',
  'Vulkan',
  'Lava',
  'Isfjell',
  'Nordlys',
  'Korallrev',
  'Regnskog',
  'Geysir',
  'Fossil',
  'Orkan',
  'Tsunami',
  'Fjord',
  'Grotte',
  'Lagune',
  'Oase',
  'Mona Lisa',
  'Viking',
  'Samurai',
  'Jazz',
  'Opera',
  'Ballett',
  'Graffiti',
  'Festival',
  'Karneval',
  'Shakespeare',
  'Picasso',
  'Bowie',
  'Banksy',
  'Mozart',
  'Hollywood',
  'Broadway',
  'Manga',
  'Flamenco',
  'Mythologi',
  'Tango',
  'Afterparty',
  'Cocktail',
  'Champagne',
  'Casino',
  'Tinder',
  'Date',
  'Eks',
  'Sjalusi',
  'Skandale',
  'Rykte',
  'Kjendis',
  'Luksus',
  'Privatfly',
  'Nattklubb',
  'VIP',
  'Karaoke',
  'Tattoo',
  'Botox',
  'Paparazzi',
  'Millionær',
  'Agent',
  'Diamantkupp',
  'Ubåt',
  'Helikopter',
  'Zeppelin',
  'Orientekspressen',
  'Tidsmaskin',
  'Labyrint',
  'Skattejakt',
  'Escape room',
  'Auksjon',
  'Museum',
  'Operaen',
  'Sirkus',
  'Børsen',
  'Ambassade',
  'Penthouse',
  'Cruiseskip',
  'Øde øy',
  'Vingård',
  'Fyrtårn',
  'Slott',
  'Katedral',
  'Templer',
  'Marked',
  'Basar',
  'Safari',
  'Karibien',
  'Ibiza',
  'Marrakech',
  'Havana',
  'Singapore',
  'Seoul',
  'Kyoto',
  'Athen',
  'Istanbul',
  'Cape Town',
  'Mexico City',
  'Los Angeles',
  'San Francisco',
  'Lasagne',
  'Macaron',
  'Fondue',
  'Pho',
  'Burrito',
  'Nachos',
  'Dim sum',
  'Pesto',
  'Focaccia',
  'Chili',
  'Avokado',
  'Østers',
  'Hummer',
  'Biff',
  'Risotto',
  'Donut',
  'Milkshake',
  'Mojito',
  'Whisky',
  'Martini',
  'Podcast',
  'Influencer',
  'Memes',
  'Realityshow',
  'Oscar',
  'Grammy',
  'Super Bowl',
  'Formel 1',
  'Wimbledon',
  'Champions League',
  'Netflix',
  'TikTok',
  'YouTube',
  'Tesla',
  'Bitcoin',
  'Kryptovaluta',
  'Robot',
  'Kunstig intelligens',
  'Hacker',
  'Dataspill',
  'Virtual reality',
  'Avatar',
  'Superhelt',
  'Vampyr',
  'Zombie',
  'Drage',
  'Enhjørning',
  'Heks',
  'Trollmann',
  'Sherlock Holmes',
  'James Bond',
  'Indiana Jones',
  'Batman',
  'Joker',
  'Dronning',
  'Keiser',
  'Pirat',
  'Gladiator',
  'Ninja',
  'Cowboy',
  'Astronomi',
  'Pyramide',
  'Solsikke',
  'Bonsai',
  'Lavendel',
  'Kaktus',
  'Orkidé',
  'Bumerang',
  'Hengekøye',
  'Kajakk',
  'Surfebrett',
  'Snowboard',
  'Fallskjerm',
  'Dykking',
  'Fjellklatring',
  'Maraton',
  'Yoga',
  'Badstue',
  'Spa',
  'Meditasjon',
  'Hypnose',
];

const droyWords = [
  'Sexstilling',
  'Kamasutra',
  'Kondom',
  'Strippeklubb',
  'OnlyFans',
  'Sugar daddy',
  'Las Vegas',
  'Donald Trump',
  'Kim Jong-un',
  'Pablo Escobar',
  'Mafia',
  'Diktator',
  'Illuminati',
  'Area 51',
  'Tabu',
  'Sensur',
  'Skilsmisse',
  'Blackmail',
  'Bordell',
  'Skatteparadis',
  'Walk of shame',
  'One night stand',
  'Booty call',
  'Nakenbading',
  'Pole dance',
  'Lap dance',
  'Fetisj',
  'Trekant',
  'Swingers',
  'Pornhub',
  'Playboy',
  'Hugh Hefner',
  'BDSM',
  'Safeword',
  'Strippepoker',
  'Twerking',
  'Bodyshot',
  'Teknisk knockout',
  'Fylleangst',
  'Promille',
  'Bakrus',
  'G-punkt',
  'Dirty talk',
  'Sexting',
  'Catfish',
  'Red flag',
  'Trophy wife',
  'Cougar',
  'Nattens dronning',
  'Skammekrok',
  'Pengevask',
  'Hvitvasking',
  'Korrupsjon',
  'Bestikkelse',
  'Offshore-konto',
  'Kokain',
  'Kartell',
  'Realityskandale',
  'Influencerdrama',
  'Nakenkalender',
  'Privat melding',
  'Lekket video',
  'Skandalepresse',
  'Forbudt frukt',
  'Rødt lys',
  'Champagnerom',
  'Gentlemans club',
  'Hemmelig affære',
  'Sugar baby',
  'Afterdark',
];

export const categoryPacks: WordPack[] = [
  {
    id: 'normal',
    label: 'Normal',
    color: '#2F9E44',
    words: normalWords,
  },
  {
    id: 'droy',
    label: 'Drøy',
    color: '#C1121F',
    words: droyWords,
  },
];

export const RELATED_WORDS: Record<string, string> = {
  Panter: 'Jaguar',
  Jaguar: 'Panter',
  Flamingo: 'Pingvin',
  Pingvin: 'Flamingo',
  Krokodille: 'Python',
  Python: 'Krokodille',
  Gorilla: 'Panda',
  Panda: 'Gorilla',
  Delfin: 'Hval',
  Hval: 'Delfin',
  Ørn: 'Falk',
  Falk: 'Ørn',
  Kameleon: 'Skorpion',
  Skorpion: 'Kameleon',
  Koala: 'Alpakka',
  Alpakka: 'Koala',
  Hai: 'Gepard',
  Gepard: 'Hai',
  Reinsdyr: 'Lama',
  Lama: 'Reinsdyr',
  Sushi: 'Ramen',
  Ramen: 'Sushi',
  Tapas: 'Bruschetta',
  Bruschetta: 'Tapas',
  Espresso: 'Croissant',
  Croissant: 'Espresso',
  Trøffel: 'Kaviar',
  Kaviar: 'Trøffel',
  Wasabi: 'Kimchi',
  Kimchi: 'Wasabi',
  Paella: 'Curry',
  Curry: 'Paella',
  Falafel: 'Hummus',
  Hummus: 'Falafel',
  Safran: 'Parmesan',
  Parmesan: 'Safran',
  Mango: 'Gelato',
  Gelato: 'Mango',
  Taco: 'Mozzarella',
  Mozzarella: 'Taco',
  Kompass: 'Kart',
  Kart: 'Kompass',
  Kikkert: 'Teleskop',
  Teleskop: 'Kikkert',
  Drone: 'Kamera',
  Kamera: 'Drone',
  Mikrofon: 'Vinyl',
  Vinyl: 'Mikrofon',
  Pass: 'Koffert',
  Koffert: 'Pass',
  Parfyme: 'Maskerade',
  Maskerade: 'Parfyme',
  Skateboard: 'Lasso',
  Lasso: 'Skateboard',
  Sjakk: 'Poker',
  Poker: 'Sjakk',
  Krone: 'Rustning',
  Rustning: 'Krone',
  Kapsel: 'Lommelykt',
  Lommelykt: 'Kapsel',
  Paris: 'Roma',
  Roma: 'Paris',
  Tokyo: 'Dubai',
  Dubai: 'Tokyo',
  Monaco: 'Santorini',
  Santorini: 'Monaco',
  Venezia: 'Barcelona',
  Barcelona: 'Venezia',
  København: 'Reykjavík',
  Reykjavík: 'København',
  'New York': 'Rio',
  Rio: 'New York',
  Bali: 'Galápagos',
  Galápagos: 'Bali',
  Svalbard: 'Alaska',
  Alaska: 'Svalbard',
  Sahara: 'Amazonas',
  Amazonas: 'Sahara',
  Himalaya: 'Antarktis',
  Antarktis: 'Himalaya',
  'Machu Picchu': 'Petra',
  Petra: 'Machu Picchu',
  Eiffeltårnet: 'Big Ben',
  'Big Ben': 'Eiffeltårnet',
  'Taj Mahal': 'Versailles',
  Versailles: 'Taj Mahal',
  Colosseum: 'Akropolis',
  Akropolis: 'Colosseum',
  Louvre: 'Mona Lisa',
  Stonehenge: 'Pompeii',
  Pompeii: 'Stonehenge',
  'Angkor Wat': 'Alhambra',
  Alhambra: 'Angkor Wat',
  Kreml: 'Notre-Dame',
  'Notre-Dame': 'Kreml',
  Sfinxen: 'Kilimanjaro',
  Kilimanjaro: 'Sfinxen',
  'Burj Khalifa': 'Frihetsgudinnen',
  Frihetsgudinnen: 'Burj Khalifa',
  Operahuset: 'Niagara',
  Niagara: 'Operahuset',
  Pluto: 'Neptun',
  Neptun: 'Pluto',
  Mars: 'Venus',
  Venus: 'Mars',
  Saturn: 'Jupiter',
  Jupiter: 'Saturn',
  Merkur: 'Solsystem',
  Solsystem: 'Merkur',
  Månen: 'Solen',
  Solen: 'Månen',
  Galakse: 'Melkeveien',
  Melkeveien: 'Galakse',
  Komet: 'Asteroide',
  Asteroide: 'Komet',
  Meteor: 'Supernova',
  Supernova: 'Meteor',
  Stjernetåke: 'Romstasjon',
  Romstasjon: 'Stjernetåke',
  Rakett: 'Astronaut',
  Astronaut: 'Rakett',
  Diamant: 'Rubin',
  Rubin: 'Diamant',
  Smaragd: 'Krystall',
  Krystall: 'Smaragd',
  Gull: 'Sølv',
  Sølv: 'Gull',
  Vulkan: 'Lava',
  Lava: 'Vulkan',
  Isfjell: 'Nordlys',
  Nordlys: 'Isfjell',
  Korallrev: 'Lagune',
  Lagune: 'Korallrev',
  Regnskog: 'Oase',
  Oase: 'Regnskog',
  Geysir: 'Fossil',
  Fossil: 'Geysir',
  Orkan: 'Tsunami',
  Tsunami: 'Orkan',
  Fjord: 'Grotte',
  Grotte: 'Fjord',
  'Mona Lisa': 'Picasso',
  Picasso: 'Mona Lisa',
  Viking: 'Samurai',
  Samurai: 'Viking',
  Jazz: 'Opera',
  Opera: 'Jazz',
  Ballett: 'Flamenco',
  Flamenco: 'Ballett',
  Graffiti: 'Banksy',
  Banksy: 'Graffiti',
  Festival: 'Karneval',
  Karneval: 'Festival',
  Shakespeare: 'Mozart',
  Mozart: 'Shakespeare',
  Bowie: 'Hollywood',
  Hollywood: 'Bowie',
  Broadway: 'Tango',
  Tango: 'Broadway',
  Manga: 'Mythologi',
  Mythologi: 'Manga',
  Afterparty: 'Nattklubb',
  Nattklubb: 'Afterparty',
  Cocktail: 'Champagne',
  Champagne: 'Cocktail',
  Casino: 'Las Vegas',
  Tinder: 'Date',
  Date: 'Tinder',
  Eks: 'Sjalusi',
  Sjalusi: 'Eks',
  Skandale: 'Rykte',
  Rykte: 'Skandale',
  Kjendis: 'Paparazzi',
  Paparazzi: 'Kjendis',
  Luksus: 'Privatfly',
  Privatfly: 'Luksus',
  VIP: 'Millionær',
  Millionær: 'VIP',
  Karaoke: 'Tattoo',
  Tattoo: 'Karaoke',
  Botox: 'Skilsmisse',
  Sexstilling: 'Kamasutra',
  Kamasutra: 'Sexstilling',
  Kondom: 'OnlyFans',
  OnlyFans: 'Kondom',
  Strippeklubb: 'Bordell',
  Bordell: 'Strippeklubb',
  'Sugar daddy': 'Skatteparadis',
  Skatteparadis: 'Sugar daddy',
  'Las Vegas': 'Casino',
  'Donald Trump': 'Kim Jong-un',
  'Kim Jong-un': 'Donald Trump',
  'Pablo Escobar': 'Mafia',
  Mafia: 'Pablo Escobar',
  Diktator: 'Sensur',
  Sensur: 'Diktator',
  Illuminati: 'Area 51',
  'Area 51': 'Illuminati',
  Tabu: 'Blackmail',
  Blackmail: 'Tabu',
  Skilsmisse: 'Botox',
};

export const allWords = Array.from(new Set(categoryPacks.flatMap((pack) => pack.words)));

export const wordPacks: WordPack[] = [
  {
    id: 'alt',
    label: 'Alle',
    color: '#172116',
    words: allWords,
  },
  ...categoryPacks,
];

function pickFallbackWord(words: string[]) {
  return words[Math.floor(Math.random() * words.length)];
}

export function getRelatedWord(word: string) {
  const relatedWord = RELATED_WORDS[word];

  if (relatedWord) {
    return relatedWord;
  }

  const sourcePack = categoryPacks.find((pack) => pack.words.includes(word));
  const alternatives = (sourcePack?.words ?? allWords).filter((alternative) => alternative !== word);

  return alternatives.length > 0 ? pickFallbackWord(alternatives) : word;
}
